### ISSUE TITLE
Avoid usage of msg.sender in initializers

### ISSUE THREAD

**Issue by spalladino** [district0x/memefactory-contracts#1]
DSAuth, DankToken, Registry, and other contracts use `msg.sender` in their initializers. This may set an owner of the contract, or mint tokens for, as the same account as their upgradeability owner (ie the account that has the permission to upgrade it). This causes conflicts when using the [transparent proxy pattern](https://docs.zeppelinos.org/docs/pattern.html#transparent-proxies-and-function-clashes): the upgradeability owner cannot call functions on the contract, but only proxy management functions. For this reason, we suggest adding an extra `address` parameter to all initialize functions, and use it instead of the `msg.sender`. This approach is used in OpenZeppelin's `Ownable` for instance: see the [vanilla](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/ownership/Ownable.sol#L20) and the [zos-friendly](https://github.com/OpenZeppelin/openzeppelin-eth/blob/master/contracts/ownership/Ownable.sol#L25) version.

**Comment by fbielejec** [comment]
https://github.com/district0x/memefactory-contracts/pull/4
